### ISSUE TITLE
"Sum" ends up at more than 100% due to rounding

### ISSUE THREAD

**Issue by ghost** [gn36/phpbb-ext-hookup#12]
Sorry I speak very little English :(

For "sum" there is a problem of calculation - rounding error - to total 101% = 2 lines for progress bar.

P.S. I prepare a translation in French.

Thank you for very good job ;)

**Comment by gn36** [comment]
Thank you for testing. I'll take a look into that 101% issue.

**Comment by gn36** [comment]
Simply send a pull request for the translation once it is done. Thank you!

**Comment by ghost** [comment]
Hello,

Here are my results(profits) to illustrate the problem
(Translation French / English by http://www.reverso.net)

![sum_number](https://cloud.githubusercontent.com/assets/13719304/9241030/41cbc23a-416e-11e5-89cb-3f211c66e35f.jpg)

It's number "normal" : For columns 1 - 4, the progress bar is on 2 lines.
Below, I posted(showed) pourcents instead of the numbers

![sum_purcent](https://cloud.githubusercontent.com/assets/13719304/9241093/f0fed4a4-416e-11e5-9b56-c93cbe7c07d2.jpg)

Here is the result(profit) for columns 1 - 6

col 1 : 38% + 38% + 25% + 0% = 101% = 2 lines
col 2 : 50% + 13% + 38% + 0% = 101% = 2 lines
col 3 : 13% + 50% + 38% + 0% = 101% = 2 lines
col 4 : 63% + 25% + 13% + 0% = 101% = 2 lines
col 5 : 38% + 25% + 25% + 12% = 100% = 1 lines
col 6 : 13% + 50% + 25% + 12% = 100% = 1 lines

**Comment by gn36** [comment]
Seems like I made a small rounding error there. This should be really easy to fix. I'll include that in the next bugfix release.
