### ISSUE TITLE
Bug for the translation

### ISSUE THREAD

**Issue by ghost** [gn36/phpbb-ext-hookup#23]
Hello,

I shall have some rectifications to be made in the translation in French.
I am seeing some details with the French-speaking community.
We discovered a problem in the files of the template. It is going to need to replace ":" by "{L_COLON}".
Want you that I take care of it ?

**Comment by gn36** [comment]
Which file is it?

**Comment by ghost** [comment]
It is necessary to make the correction in all the files in "template/"

With Geany or Notepad++ It is necessary to replace every "}:" by "}{L_COLON}"

In English and Deutsche : 
'COLON' => ':',

In French, we add a space before : 
'COLON' => ' :',

(https://github.com/phpbb/phpbb/blob/3.1.x/phpBB/language/en/common.php#L163)

**Comment by gn36** [comment]
I hope I didn't miss anything.

**Comment by ghost** [comment]
I shall make for you a sign if one is missing it ;-)

Thank you ;-)
