### ISSUE TITLE
Langage file: use ’ instead of \'

### ISSUE THREAD

**Issue by Skouat** [gn36/phpbb-ext-hookup#24]
Hi,

In `en/hookup.php` you must use `’` instead of `\'`.
And after apply this change, don't forget to convert your file in UTF-8 w/BOM

Lines affected :   

https://github.com/gn36/phpbb-ext-hookup/blob/master/language/en/hookup.php#L71
https://github.com/gn36/phpbb-ext-hookup/blob/master/language/en/hookup.php#L96
https://github.com/gn36/phpbb-ext-hookup/blob/master/language/en/hookup.php#L110

You can find some special chars in header of any files of phpBB English language pack.

**Comment by gn36** [comment]
Fixed in Master
