### ISSUE TITLE
E-Mails use user_id instead of username

### ISSUE THREAD

**Issue by gn36** [gn36/phpbb-ext-hookup#32]
Invitation E-Mails from the hookup use user_ids instead of usernames in the mail text.

**Comment by ChristopheTdn** [comment]
No problem here.

I use the French translation. The entete message does refer to my username 

For example  

'Bonjour ToF,

Vous recevez cette notification car vous participez à un événement planifié
dans le sujet « xxxxxxxxxxx » sur « xxxxxxxxxxx». Depuis votre dernière visite, cet événement a reçu de nouvelles dates.
 Vous pouvez utiliser le lien suivant pour voir le sujet et
l’événement planifié, aucune autre notification ne vous sera envoyée
jusqu’à votre prochaine visite sur ce sujet.

http://xxxxxx/xxxxx./xxxxxxxxx

## 

Forum  xxxxxxxx
Contact : xxxxx"

hope this help

**Comment by gn36** [comment]
Thank you. I could not reproduce the problem, either. I'll just close the issue then.

**Comment by ChristopheTdn** [comment]
you can reopen it

The error is when you invite a new participant 

exemple =

"Bonjour 2,

Vous avez été invité à participer l’événement planifié sur le sujet « xxxxxxxxxxxxxxxxx» sur « xxxxxxxxxxxxxxxx ». Consultez-le
et complétez-le dès que vous le pourrez.

Pour consulter le sujet et l’événement associé, cliquez sur le lien
suivant :
http://xxxxxx/xxxxxxxxx/viewtopic.php?t=30

**Comment by gn36** [comment]
For some reason I thought I had a central place where the username was set. Apparently not... This should really be fixed now with the newest commit.
