### ISSUE TITLE
The link returned by the Email notification is false (a point added in url)

### ISSUE THREAD

**Issue by ChristopheTdn** [gn36/phpbb-ext-hookup#36]
When you receive a email notification from the extension after adding a new date, a point is automaticaly added to the URL.

exemple
http://mysite.com/phpbb./viewtopic.php?t=30

as you can see, there is a point after phpbb

Thx for your greet work !!!!

**Comment by gn36** [comment]
Please check if this fixes it.

And thank you for reporting!

**Comment by gn36** [comment]
By the way, can you confirm bug #32? It was reported to me, but I could not see an error in my code.

**Comment by ChristopheTdn** [comment]
your last modification fixe the error.

for bug #32 i update my feedback, error is only when you add a new participant.

Thx !!!
