### ISSUE TITLE
no DATE In EMAIL Notification

### ISSUE THREAD

**Issue by ChristopheTdn** [gn36/phpbb-ext-hookup#37]
When you validate the date.

The notification mail is incomplete. No date in it (French translation):
##  for exemple  =

"Bonjour ToF,

Vous recevez cette notification car vous participez à un événement planifié
dans le sujet « date de reunion XXXX » à « XXXXXXXXXXXXXXXXXXXXXX ».

La date de l’événement a été fixé au :

Pour consulter le sujet et l’événement associé, cliquez sur le lien
suivant :
http://www.XXXX.XX/phpbb/viewtopic.php?t=30
## 

As you can see there is nothing after "La date de l’événement a été fixé au :"

Thx for your excellent work !!!

**Comment by gn36** [comment]
Thanks for reporting. I will look into this.

**Comment by gn36** [comment]
I hope this will fix it.
