### ISSUE TITLE
Not able to add User, even tho he has read/write permission for the forum

### ISSUE THREAD

**Issue by BenniGotchi** [gn36/phpbb-ext-hookup#39]
When I want to add a single user or a group of users to a hookup, I get a error message:

The user xxx doesn’t have the permission to read this forum (USER_CANNOT_READ_FORUM)

This happens, but all the users actually have appropriate rights, to read and write in the forum.

Taking a look into the code, I found, that there is a second condition, that is checked, which leads to the 'USER_CANNOT_READ_FORUM' error message:

 phpbb-ext-hookup/event/viewtopic.php (lines 629-633):

```
            if (!$user_auth->acl_get('f_read', $event['forum_id']) || !$user_auth->acl_get('f_hookup', $event['forum_id']))
            {
                $hookup_errors[] = sprintf($this->user->lang['USER_CANNOT_READ_FORUM'], $new_users[$user_id]['username']);
                unset($userids_to_add[$key]);
            }
```

I think, the second part in the if() shouldn't be there, since the ACL rule should manage (at least from my understanding and from the explanation in permissions_hookup.php), if someone is allowed to create a new hookup. But here it's only about adding a user to be able to vote.

**Comment by gn36** [comment]
Actually, the only thing that is wrong is the error message. f_hookup is the permission to see and use hookups. The user needs to have that as well.

**Comment by gn36** [comment]
The newest Version should now generate two separate messages: One for not being able to read the forum, the other for not being able to see hookups.
