### ISSUE TITLE
French translation incomplete

### ISSUE THREAD

**Issue by gn36** [gn36/phpbb-ext-hookup#44]
The french translation is missing a few new things.

@MetallicaMust Could you adjust the french translation so it matches the new version? I have changed a few things and there are new translation files that are missing in the french version. My french is not good enough to do this myself.

**Comment by gn36** [comment]
Just for your information, these are the current differences between en/ and fr/:

```
 Fatal in email/hookup_active_date_reset.txt:
Missing required file

 Fatal in email/hookup_added_user.txt:
Missing required file

 Fatal in global.php:
Missing required file

 Fatal in info_ucp_hookup.php:
Missing required file

 Fatal in hookup.php:USERNAMES_EXPLAIN:
String is using additional html: <span style="text-decoration: underline;">

 Fatal in hookup.php:
Must contain key: HOOKUP_AUTORESET_ACTIVE_DESC

 Error in email/hookup_active_date.txt:
Is not using variables: {ACTIVE_DATE_SHORT}
```

**Comment by gn36** [comment]
@MetallicaMust please correct the french translation. Otherwise I will have to throw it out, as it is incomplete.

**Comment by ChristopheTdn** [comment]
i can make the french translation for you if you want (i m french)

i take a look and send you appropriate file

**Comment by gn36** [comment]
Sure, that would be great! Note that there is already a partial translation present that you can use as a base.

**Comment by ChristopheTdn** [comment]
ok. I fork the source and have a look. Expect some progress for tomorrow and monday for a full translation

**Comment by ChristopheTdn** [comment]
i try to make a pull request. Not very familiar with GIT HUB interface. Let me know if there s a problem.

*_i merged a branch *_> "Merge remote-tracking branch 'refs/remotes/gn36/dev/translation-valid"

dont understand how ???   

You can find new  FR File in the langage directory.
