### ISSUE TITLE
Username of the creator instead of the recipient in german emails

### ISSUE THREAD

**Issue by Mudhenn** [gn36/phpbb-ext-hookup#53]
Hello
when I (Frank) add dates to the survey it sends an email to every user which is part of it. Unfortunatly, the mail to the user "Hannes" starts with "Hallo Frank" instead wiht "Hallo Hannes". I can't find any difference in the .txt-files so I'm kind of lost where to look for it.

Thanks for that great extension nonetheless!

best regards,
Frank

**Comment by gn36** [comment]
Which language are you using? German I guess? 

What phpBB Version do you use? 3.1.9?

I will take a look into the message generation. Maybe I am using the wrong variable.

**Comment by Mudhenn** [comment]
Hello
I'm using 3.1.9 from phpBB.de and German as default language.
TIA!

**Comment by ChristopheTdn** [comment]
Hi,
Same problem in  the french version...
