### ISSUE TITLE
After uploading the new files phpBB crashes on start

### ISSUE THREAD

**Issue by Mudhenn** [gn36/phpbb-ext-hookup#54]
"Catchable fatal error: Argument 6 passed to gn36\hookup\cron\hookup_weekly_reset::__construct() must implement interface phpbb\event\dispatcher_interface, string given, called in /home/.sites/125/site129/web/rpg/cache/container_0374ec857381230fa83049643ce3cdee.php on line 1422 and defined in /home/.sites/125/site129/web/rpg/ext/gn36/hookup/cron/hookup_weekly_reset.php on line 49"

**Comment by Mudhenn** [comment]
When I change it back to the old hookup_weekly_reset.php it works again...

**Comment by gn36** [comment]
Did you clear the cache or disable/enable the extension for the upgrade?

This looks like a stale cache problem. I needed additional objects to add the new notification.

**Comment by Mudhenn** [comment]
Sorry, seems to be my fault, I just copied the new files and didn't deactivated it, 
Sorry again!
